In [1]:
import pandas as pd
import numpy as np
import zipfile
import gzip
import os
import json
import time
import matplotlib.pyplot as plt
from tqdm import tqdm
import pymysql
from sqlalchemy import create_engine

In [52]:
# set path
path = 'D:/owl-data/Event Stream Data/2020 Season Match Data/'
dir_list = os.listdir(path)

# get folder list
folder_list = []
for f in dir_list:
    if os.path.isdir(path + f):
        folder_list.append(f)
folder_list = folder_list[:-2] # remove 'guids' folder

df1 = pd.DataFrame()
df2 = pd.DataFrame()
for f in folder_list:
    file_list = os.listdir(path + f)
    file_list = [file for file in file_list if file.endswith('.gz')] # get gz files only
    gamestart_file_name = [g for g in file_list if 'gamestart' in g] # return gamestart file names
    gameresult_file_name = [g for g in file_list if 'gameresult' in g] # return gamestart file names
    print(gamestart_file_name)
    print(gameresult_file_name)

    df_gamestart = pd.read_csv(os.path.join(path, f, gamestart_file_name[0]), delimiter = '\t', compression='gzip')
    df1 = pd.concat([df1, df_gamestart], axis=0, ignore_index=True) # concat data info df
    df_gameresult = pd.read_csv(os.path.join(path, f, gameresult_file_name[0]), delimiter = '\t', compression='gzip')
    df2 = pd.concat([df2, df_gameresult], axis=0, ignore_index=True) # concat data info df
display(df1)
display(df2)

['payload_gamestart-20200622.tsv.gz']
['payload_gameresult-20200622.tsv.gz']
['payload_gamestart-20200622-20200628.tsv.gz']
['payload_gameresult-20200622-20200628.tsv.gz']
['payload_gamestart-20200629-20200705.tsv.gz']
['payload_gameresult-20200629-20200705.tsv.gz']
['payload_gamestart-20200713-20200719.tsv.gz']
['payload_gameresult-20200713-20200719.tsv.gz']
['payload_gamestart-20200720-20200726.tsv.gz']
['payload_gameresult-20200720-20200726.tsv.gz']
['payload_gamestart-20200727-20200802.tsv.gz']
['payload_gameresult-20200727-20200802.tsv.gz']
['payload_gamestart-20200803-20200809.tsv.gz']
['payload_gameresult-20200803-20200809.tsv.gz']
['payload_gamestart-20200810-20200816.tsv.gz']
['payload_gameresult-20200810-20200816.tsv.gz']

,time_c,schema_name,time,info,players,map_guid,esports_match_id
0,2020-06-20 08:19:07,GameStart,1592641147850,"{""event_id"":29,""sequence_length"":1,""sequence_i...","[{""base_player"":{""player_id"":{""src"":0,""seq"":12...",576460752303425122,34622
1,2020-06-20 08:42:45,GameStart,1592642565001,"{""event_id"":27,""sequence_length"":1,""sequence_i...","[{""base_player"":{""player_id"":{""src"":0,""seq"":19...",576460752303425649,34622
2,2020-06-20 09:08:59,GameStart,1592644139326,"{""event_id"":29,""sequence_length"":1,""sequence_i...","[{""base_player"":{""player_id"":{""src"":0,""seq"":19...",576460752303425374,34622
3,2020-06-20 09:37:56,GameStart,1592645876186,"{""event_id"":27,""sequence_length"":1,""sequence_i...","[{""base_player"":{""player_id"":{""src"":0,""seq"":19...",576460752303423963,34622
4,2020-06-20 10:01:20,GameStart,1592647280384,"{""event_id"":30,""sequence_length"":1,""sequence_i...","[{""base_player"":{""player_id"":{""src"":0,""seq"":19...",576460752303425506,34622
...,...,...,...,...,...,...,...
419,2020-08-16 21:41:48,GameStart,1597614108494,"{""event_id"":37,""sequence_length"":1,""sequence_i...","[{""base_player"":{""player_id"":{""src"":0,""seq"":67...",576460752303426116,34766
420,2020-08-16 22:11:59,GameStart,1597615919992,"{""event_id"":27,""sequence_length"":1,""sequence_i...","[{""base_player"":{""player_id"":{""src"":0,""seq"":67...",576460752303425133,34766
421,2020-08-16 22:40:29,GameStart,1597617629681,"{""event_id"":29,""sequence_length"":1,""sequence_i...","[{""base_player"":{""player_id"":{""src"":0,""seq"":12...",576460752303425182,34765
422,2020-08-16 22:55:58,GameStart,1597618558831,"{""event_id"":30,""sequence_length"":1,""sequence_i...","[{""base_player"":{""player_id"":{""src"":0,""seq"":52...",576460752303425165,34765
423,2020-08-16 23:29:54,GameStart,1597620594279,"{""event_id"":33,""sequence_length"":1,""sequence_i...","[{""base_player"":{""player_id"":{""src"":0,""seq"":52...",576460752303423963,34765

,time_c,schema_name,time,info,winningteamid,score_info,players,total_game_time_ms,end_reason,esports_match_id
0,2020-06-20 08:36:16,GameResult,1592642176669,"{""event_id"":2915,""sequence_length"":132,""sequen...",37c4bff4-e644-2541-91e4-b1a7a9914d27,"{""round_num"":3,""attacking_team_id"":""14e7f1ad-b...","[{""base_player"":{""player_id"":{""src"":0,""seq"":12...",1019381,NORMAL,34622
1,2020-06-20 08:57:46,GameResult,1592643466019,"{""event_id"":2460,""sequence_length"":81,""sequenc...",37c4bff4-e644-2541-91e4-b1a7a9914d27,"{""round_num"":2,""attacking_team_id"":""14e7f1ad-b...","[{""base_player"":{""player_id"":{""src"":0,""seq"":19...",896424,NORMAL,34622
2,2020-06-20 09:32:10,GameResult,1592645530534,"{""event_id"":3631,""sequence_length"":111,""sequen...",14e7f1ad-bc68-854c-8479-a9ca15ca03fd,"{""round_num"":4,""attacking_team_id"":""14e7f1ad-b...","[{""base_player"":{""player_id"":{""src"":0,""seq"":19...",1377425,NORMAL,34622
3,2020-06-20 09:56:04,GameResult,1592646964972,"{""event_id"":2845,""sequence_length"":96,""sequenc...",14e7f1ad-bc68-854c-8479-a9ca15ca03fd,"{""round_num"":4,""attacking_team_id"":""14e7f1ad-b...","[{""base_player"":{""player_id"":{""src"":0,""seq"":19...",1075007,NORMAL,34622
4,2020-06-20 10:16:52,GameResult,1592648212022,"{""event_id"":2673,""sequence_length"":144,""sequen...",37c4bff4-e644-2541-91e4-b1a7a9914d27,"{""round_num"":3,""attacking_team_id"":""14e7f1ad-b...","[{""base_player"":{""player_id"":{""src"":0,""seq"":19...",922199,NORMAL,34622
...,...,...,...,...,...,...,...,...,...,...
417,2020-08-16 22:05:58,GameResult,1597615558989,"{""event_id"":3837,""sequence_length"":168,""sequen...",cbe0e747-c919-c04a-9f9c-cdbe3ae7e7c0,"{""round_num"":4,""attacking_team_id"":""61c6c799-3...","[{""base_player"":{""player_id"":{""src"":0,""seq"":67...",1436714,NORMAL,34766
418,2020-08-16 22:23:00,GameResult,1597616580360,"{""event_id"":1781,""sequence_length"":129,""sequen...",cbe0e747-c919-c04a-9f9c-cdbe3ae7e7c0,"{""round_num"":2,""attacking_team_id"":""61c6c799-3...","[{""base_player"":{""player_id"":{""src"":0,""seq"":67...",655648,NORMAL,34766
419,2020-08-16 22:48:55,GameResult,1597618135965,"{""event_id"":1395,""sequence_length"":126,""sequen...",3dfb307c-5c7a-bc48-9e41-96a3cbcc414f,"{""round_num"":2,""attacking_team_id"":""6df3c959-3...","[{""base_player"":{""player_id"":{""src"":0,""seq"":12...",501563,NORMAL,34765
420,2020-08-16 23:12:47,GameResult,1597619567173,"{""event_id"":2864,""sequence_length"":135,""sequen...",6df3c959-372b-954b-a03b-211d9d80c089,"{""round_num"":2,""attacking_team_id"":""6df3c959-3...","[{""base_player"":{""player_id"":{""src"":0,""seq"":52...",1003750,NORMAL,34765
421,2020-08-16 23:54:45,GameResult,1597622085567,"{""event_id"":3782,""sequence_length"":165,""sequen...",6df3c959-372b-954b-a03b-211d9d80c089,"{""round_num"":4,""attacking_team_id"":""3dfb307c-5...","[{""base_player"":{""player_id"":{""src"":0,""seq"":52...",1322694,NORMAL,34765

In [86]:
# add map_guid column in gameresult df
def get_map_guid(str):
    '''
    args, json text from gameresult
    target, map_guid
    '''
    jsontxt = json.loads(str)
    map_guid = jsontxt['game_context']['map_guid']
    
    return map_guid

map_guid_list = []
for idx in df2.index:
    map_guid = get_map_guid(df2.loc[idx, 'info'])
    map_guid_list.append(map_guid)

df2['map_guid'] = map_guid_list
df2 = df2[df2['end_reason'] == 'NORMAL']
display(df2)

,time_c,schema_name,time,info,winningteamid,score_info,players,total_game_time_ms,end_reason,esports_match_id,map_guid
0,2020-06-20 08:36:16,GameResult,1592642176669,"{""event_id"":2915,""sequence_length"":132,""sequen...",37c4bff4-e644-2541-91e4-b1a7a9914d27,"{""round_num"":3,""attacking_team_id"":""14e7f1ad-b...","[{""base_player"":{""player_id"":{""src"":0,""seq"":12...",1019381,NORMAL,34622,576460752303425122
1,2020-06-20 08:57:46,GameResult,1592643466019,"{""event_id"":2460,""sequence_length"":81,""sequenc...",37c4bff4-e644-2541-91e4-b1a7a9914d27,"{""round_num"":2,""attacking_team_id"":""14e7f1ad-b...","[{""base_player"":{""player_id"":{""src"":0,""seq"":19...",896424,NORMAL,34622,576460752303425649
2,2020-06-20 09:32:10,GameResult,1592645530534,"{""event_id"":3631,""sequence_length"":111,""sequen...",14e7f1ad-bc68-854c-8479-a9ca15ca03fd,"{""round_num"":4,""attacking_team_id"":""14e7f1ad-b...","[{""base_player"":{""player_id"":{""src"":0,""seq"":19...",1377425,NORMAL,34622,576460752303425374
3,2020-06-20 09:56:04,GameResult,1592646964972,"{""event_id"":2845,""sequence_length"":96,""sequenc...",14e7f1ad-bc68-854c-8479-a9ca15ca03fd,"{""round_num"":4,""attacking_team_id"":""14e7f1ad-b...","[{""base_player"":{""player_id"":{""src"":0,""seq"":19...",1075007,NORMAL,34622,576460752303423963
4,2020-06-20 10:16:52,GameResult,1592648212022,"{""event_id"":2673,""sequence_length"":144,""sequen...",37c4bff4-e644-2541-91e4-b1a7a9914d27,"{""round_num"":3,""attacking_team_id"":""14e7f1ad-b...","[{""base_player"":{""player_id"":{""src"":0,""seq"":19...",922199,NORMAL,34622,576460752303425506
...,...,...,...,...,...,...,...,...,...,...,...
417,2020-08-16 22:05:58,GameResult,1597615558989,"{""event_id"":3837,""sequence_length"":168,""sequen...",cbe0e747-c919-c04a-9f9c-cdbe3ae7e7c0,"{""round_num"":4,""attacking_team_id"":""61c6c799-3...","[{""base_player"":{""player_id"":{""src"":0,""seq"":67...",1436714,NORMAL,34766,576460752303426116
418,2020-08-16 22:23:00,GameResult,1597616580360,"{""event_id"":1781,""sequence_length"":129,""sequen...",cbe0e747-c919-c04a-9f9c-cdbe3ae7e7c0,"{""round_num"":2,""attacking_team_id"":""61c6c799-3...","[{""base_player"":{""player_id"":{""src"":0,""seq"":67...",655648,NORMAL,34766,576460752303425133
419,2020-08-16 22:48:55,GameResult,1597618135965,"{""event_id"":1395,""sequence_length"":126,""sequen...",3dfb307c-5c7a-bc48-9e41-96a3cbcc414f,"{""round_num"":2,""attacking_team_id"":""6df3c959-3...","[{""base_player"":{""player_id"":{""src"":0,""seq"":12...",501563,NORMAL,34765,576460752303425182
420,2020-08-16 23:12:47,GameResult,1597619567173,"{""event_id"":2864,""sequence_length"":135,""sequen...",6df3c959-372b-954b-a03b-211d9d80c089,"{""round_num"":2,""attacking_team_id"":""6df3c959-3...","[{""base_player"":{""player_id"":{""src"":0,""seq"":52...",1003750,NORMAL,34765,576460752303425165
421,2020-08-16 23:54:45,GameResult,1597622085567,"{""event_id"":3782,""sequence_length"":165,""sequen...",6df3c959-372b-954b-a03b-211d9d80c089,"{""round_num"":4,""attacking_team_id"":""3dfb307c-5...","[{""base_player"":{""player_id"":{""src"":0,""seq"":52...",1322694,NORMAL,34765,576460752303423963

In [92]:
# merge df1(gamestart) and df2(gameresult)
df_merge = pd.merge(df1, df2, how='left', left_on=['map_guid', 'esports_match_id'], right_on=['map_guid', 'esports_match_id'], suffixes=('_gamestart', '_gameresult'))
df_merge = df_merge[['time_gamestart', 'map_guid', 'esports_match_id', 'time_gameresult']]
display(df_merge)

     time_gamestart            map_guid  esports_match_id  time_gameresult
0     1592641147850  576460752303425122             34622    1592642176669
1     1592642565001  576460752303425649             34622    1592643466019
2     1592644139326  576460752303425374             34622    1592645530534
3     1592645876186  576460752303423963             34622    1592646964972
4     1592647280384  576460752303425506             34622    1592648212022
..              ...                 ...               ...              ...
419   1597614108494  576460752303426116             34766    1597615558989
420   1597615919992  576460752303425133             34766    1597616580360
421   1597617629681  576460752303425182             34765    1597618135965
422   1597618558831  576460752303425165             34765    1597619567173
423   1597620594279  576460752303423963             34765    1597622085567

[424 rows x 4 columns]

In [93]:
# map_guid mapping
map_guid = pd.read_csv((os.path.join('D:\owl-data\guid', 'map_guid.csv')), delimiter=',')
display(map_guid)
df_ = pd.merge(df_merge, map_guid, how='left', left_on='map_guid', right_on='guid')
display(df_)

              en_map_name                guid
0        Temple of Anubis  576460752303423579
1              King's Row  576460752303423700
2                Hanamura  576460752303423845
3   Watchpoint: Gibraltar  576460752303423876
4                 Numbani  576460752303423956
..                    ...                 ...
69                  Paris  576460752303426288
70                 Havana  576460752303426302
71                 Havana  576460752303426389
72            Eichenwalde  576460752303426564
73           Black Forest  576460752303426657

[74 rows x 2 columns]

,time_gamestart,map_guid,esports_match_id,time_gameresult,en_map_name,guid
0,1592641147850,576460752303425122,34622,1592642176669,Lijiang Tower,576460752303425122
1,1592642565001,576460752303425649,34622,1592643466019,Rialto,576460752303425649
2,1592644139326,576460752303425374,34622,1592645530534,Blizzard World,576460752303425374
3,1592645876186,576460752303423963,34622,1592646964972,Volskaya Industries,576460752303423963
4,1592647280384,576460752303425506,34622,1592648212022,Busan,576460752303425506
...,...,...,...,...,...,...
419,1597614108494,576460752303426116,34766,1597615558989,Havana,576460752303426116
420,1597615919992,576460752303425133,34766,1597616580360,Ilios,576460752303425133
421,1597617629681,576460752303425182,34765,1597618135965,Oasis,576460752303425182
422,1597618558831,576460752303425165,34765,1597619567173,Eichenwalde,576460752303425165
423,1597620594279,576460752303423963,34765,1597622085567,Volskaya Industries,576460752303423963

In [94]:
# save df to pickle
df_ = df_[['time_gamestart', 'time_gameresult', 'esports_match_id', 'en_map_name', 'map_guid']]
display(df_)
df_.to_pickle(os.path.join('D:\owl-data\pickles', 'OWL_map_start_info'))

,time_gamestart,time_gameresult,esports_match_id,en_map_name,map_guid
0,1592641147850,1592642176669,34622,Lijiang Tower,576460752303425122
1,1592642565001,1592643466019,34622,Rialto,576460752303425649
2,1592644139326,1592645530534,34622,Blizzard World,576460752303425374
3,1592645876186,1592646964972,34622,Volskaya Industries,576460752303423963
4,1592647280384,1592648212022,34622,Busan,576460752303425506
...,...,...,...,...,...
419,1597614108494,1597615558989,34766,Havana,576460752303426116
420,1597615919992,1597616580360,34766,Ilios,576460752303425133
421,1597617629681,1597618135965,34765,Oasis,576460752303425182
422,1597618558831,1597619567173,34765,Eichenwalde,576460752303425165
423,1597620594279,1597622085567,34765,Volskaya Industries,576460752303423963

In [95]:
# read pickle
test = pd.read_pickle(os.path.join('D:\owl-data\pickles', 'OWL_map_start_info'))
display(test)

,time_gamestart,time_gameresult,esports_match_id,en_map_name,map_guid
0,1592641147850,1592642176669,34622,Lijiang Tower,576460752303425122
1,1592642565001,1592643466019,34622,Rialto,576460752303425649
2,1592644139326,1592645530534,34622,Blizzard World,576460752303425374
3,1592645876186,1592646964972,34622,Volskaya Industries,576460752303423963
4,1592647280384,1592648212022,34622,Busan,576460752303425506
...,...,...,...,...,...
419,1597614108494,1597615558989,34766,Havana,576460752303426116
420,1597615919992,1597616580360,34766,Ilios,576460752303425133
421,1597617629681,1597618135965,34765,Oasis,576460752303425182
422,1597618558831,1597619567173,34765,Eichenwalde,576460752303425165
423,1597620594279,1597622085567,34765,Volskaya Industries,576460752303423963